spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: false
  jms:
    pub-sub-domain: true

# 队列和订阅目的地
topicDestinationName1:
topicDestinationName2:
queueDestinationName1:
queueDestinationName2: